// Test fixture: ts-rs generated bindings file
// ts-rs can generate type definitions and optionally command bindings

import { invoke } from '@tauri-apps/api/core';

// Type definitions generated by ts-rs
export type User = { id: number; name: string; email: string };
export type Preferences = { theme: string; language: string };

// Command bindings (custom integration with ts-rs types)
export const commands = {
  async getUserProfile(userId: number): Promise<User> {
    return await invoke("get_user_profile", { userId });
  },

  async savePreferences(prefs: Preferences): Promise<void> {
    return await invoke("save_preferences", { prefs });
  },

  async deleteItem(id: number): Promise<void> {
    return await invoke("delete_item", { id });
  },

  async listUsers(): Promise<User[]> {
    return await invoke("list_users");
  }
};
