// This file was generated by [tauri-specta]. Do not edit.

export const commands = {
    async getUserProfile(id: number): Promise<Result<UserProfile, string>> {
        return await invoke("get_user_profile", { id });
    },
    async createUser(name: string, age: number): Promise<Result<User, string>> {
        return await invoke("create_user", { name, age });
    },
    async ping(): Promise<void> {
        return await invoke("ping");
    },
};
