/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-01-01T00:00:00.000000000+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

export type SimpleUser = { id: number; username: string };
export type ApiResponse = { data: string; status: number };
export type TaskState = "Idle" | "Running" | "Error";

export interface UserProfile {
  id: number;
  name: string;
  email: string;
  active: boolean;
}

export interface GreetParams {
  name: string;
  [key: string]: unknown;
}

export interface GetUserProfileParams {
  userId: number;
  [key: string]: unknown;
}
