use lsp_server::bindings_reader::{find_bindings_file, read_bindings};
use lsp_server::indexer::ProjectIndex;
use std::fs::File;
use std::io::Write;
use tempfile::tempdir;

#[test]
fn test_find_bindings_file_in_src() {
    let dir = tempdir().unwrap();
    let project_root = dir.path();
    let bindings_path = project_root.join("src/bindings.ts");

    std::fs::create_dir_all(project_root.join("src")).unwrap();
    File::create(&bindings_path).unwrap();

    let found = find_bindings_file(project_root);
    assert_eq!(found, Some(bindings_path.canonicalize().unwrap()));
}

#[test]
fn test_find_bindings_via_specta_export() {
    let dir = tempdir().unwrap();
    let project_root = dir.path();

    // Create src-tauri/src/main.rs with export call
    let src_tauri = project_root.join("src-tauri/src");
    std::fs::create_dir_all(&src_tauri).unwrap();

    let main_rs = src_tauri.join("main.rs");
    let mut file = File::create(&main_rs).unwrap();
    writeln!(
        file,
        r#"
        fn main() {{
            ts::export(collect_types![cmd], "bindings.ts").unwrap();
        }}
    "#
    )
    .unwrap();

    // Create the bindings file where it points to
    let bindings_path = project_root.join("src-tauri/bindings.ts");
    File::create(&bindings_path).unwrap();

    let found = find_bindings_file(project_root);
    assert_eq!(found, Some(bindings_path.canonicalize().unwrap()));
}

#[test]
fn test_read_bindings_simple() {
    let dir = tempdir().unwrap();
    let bindings_path = dir.path().join("bindings.ts");

    let mut file = File::create(&bindings_path).unwrap();
    writeln!(
        file,
        r#"
        /* eslint-disable */
        // This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta)

        export async function getUser(id: number): Promise<User> {{
            return await TAURI_INVOKE("getUser", {{ id }});
        }}

        export async function saveData(data: string, options?: any): Promise<void> {{
            return await TAURI_INVOKE("save_data", {{ data, options }});
        }}
        
        export function synchronousCmd(): void {{
            return TAURI_INVOKE("synchronous_cmd");
        }}
    "#
    )
    .unwrap();

    let index = ProjectIndex::new();
    read_bindings(&bindings_path, &index).unwrap();

    assert_eq!(index.bindings_cache.len(), 3);

    // Check getUser
    let user_cmd = index.bindings_cache.get("getUser").unwrap();
    assert_eq!(user_cmd.command_name, "getUser");

    // Check saveData (snake_case conversion test? generic parser logic?)
    // The current parser uses the function name as command name.
    // If specta generates "saveData" for Rust "save_data",
    // we need to know how to map it.
    // Usually Specta preserves renaming if configured.
    let save_cmd = index.bindings_cache.get("saveData").unwrap();
    assert_eq!(save_cmd.command_name, "saveData");
}
